owner: renchix  # Replace with your actual GitHub username/org
repo: catego-status                 # Replace with your repository name

user-agent: Catego-Uptime-Bot

# List of endpoints to track
sites:
  - name: Catego AIS API
    url: https://ais.catego.app/health
  - name: Admin Portal
    url: https://ais-portal.catego.app
  - name: Auth Gateway
    url: https://connect.catego.app

status-website:
  # Add the GitHub repository name using the baseUrl setting
  baseUrl: /catego-status
  logoUrl: https://connect.catego.app/favicon.svg
  name: Catego System Status
  introTitle: "Real-time system status for Catego Open Banking."
  introMessage: "Welcome to the Catego status page. Here you can monitor our API uptime and operational health."
